apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
 name: guestbookapppropagation
spec:
 resourceSelectors:
     #Frontend guestbook
   - apiVersion: apps/v1
     kind: Deployment
     name: guestbookfrontend
   - apiVersion: v1
     kind: Service
     name: guestbookfrontend
 placement:
   clusterAffinity:
     clusterNames:
       - eu
       - ap
       - us
   replicaScheduling:
     replicaDivisionPreference: Weighted
     replicaSchedulingType: Divided
     weightPreference:
       staticWeightList:
         - targetCluster:
             clusterNames:
               - us
           weight: 3
         - targetCluster:
             clusterNames:
               - ap
           weight: 3
         - targetCluster:
             clusterNames:
               - eu
           weight: 3