apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
 name: guest_book_app_propagation
spec:
 resourceSelectors:
     #Frontend guestbook
   - apiVersion: apps/v1
     kind: Deployment
     name: frontend
   - apiVersion: v1
     kind: Service
     name: frontend
     #Redis Leader
   - apiVersion: apps/v1
     kind: Deployment
     name: redis-leader
   - apiVersion: v1
     kind: Service
     name: redis-leader
    #Redis Follower
   - apiVersion: apps/v1
     kind: Deployment
     name: redis-follower
   - apiVersion: v1
     kind: Service
     name: redis-follower
 placement:
   clusterAffinity:
     clusterNames:
       - eu
       - ap
       - us
   replicaScheduling:
     replicaDivisionPreference: Weighted
     replicaSchedulingType: Divided
     weightPreference:
       staticWeightList:
         - targetCluster:
             clusterNames:
               - us
           weight: 1
         - targetCluster:
             clusterNames:
               - ap
           weight: 1
         - targetCluster:
             clusterNames:
               - eu
           weight: 1